"""Deterministic context windows and conversation reliability audits."""

from .adapters import (
    ChatFormat,
    adapt_anthropic,
    adapt_conversation,
    adapt_convokit,
    adapt_openai,
    adapt_sharegpt,
    iter_adapted_conversations,
    iter_adapted_convokit_jsonl,
    iter_adapted_jsonl,
    iter_adapted_path,
)
from .audit import Auditor, default_auditor
from .builder import ContextBuilder
from .classifier import ClassifierState, ConversationClassifier
from .coordination import ReplyCoordinationScore, reply_coordination
from .corpus import CorpusStore
from .dual_context import (
    ClusterState,
    ContextEdge,
    ContextProjection,
    ContextRecord,
    DirectionPrediction,
    DirectionState,
    DualContextConfig,
    DualContextModel,
    DualContextPrediction,
    DualContextState,
)
from .dual_context_evaluation import evaluate_dual_context
from .expected_context import (
    ContextPair,
    ContextPrediction,
    ExpectedContextModel,
    ExpectedContextState,
    iter_context_pairs,
)
from .forecast import ForecastPrediction, ForecastState, PrefixEventForecaster
from .forecast_data import (
    ForecastDataset,
    ForecastExample,
    ForecastPrefix,
    prepare_forecast_examples,
)
from .graph import (
    InteractionEdge,
    InteractionNetwork,
    InteractionNetworkAccumulator,
    NetworkCentrality,
    NetworkEdge,
    NetworkMetrics,
    ReplyForest,
    SpeakerSummary,
    interaction_edges,
    interaction_network,
    reply_forest,
)
from .io import iter_conversations, iter_path
from .models import AuditReport, ContextWindow, Conversation, Issue, Severity, Utterance
from .neural_forecast import (
    HierarchicalEventForecaster,
    NeuralForecastConfig,
    NeuralForecastPrediction,
    NeuralForecastState,
)
from .neural_forecast_artifact import (
    NeuralArtifactError,
    NeuralArtifactLimits,
    NeuralSaveResult,
    load_neural_forecaster,
    save_neural_forecaster,
)
from .neural_forecast_data import (
    ObservedPrefix,
    ObservedTurn,
    SequenceAudit,
    SequenceDataError,
    SequenceForecastDataset,
    SequenceForecastExample,
    SequenceLimitError,
    SequenceLimits,
    SequencePolicy,
    observed_prefix,
    prepare_sequence_forecasts,
)
from .neural_forecast_math import NeuralArchitecture, NeuralNumericLimits
from .neural_forecast_train import NeuralEpoch, NeuralTrainingConfig, NeuralTrainingResult
from .neural_token_data import (
    EncodedPrefix,
    SequenceVocabulary,
    encode_observed_prefix,
    fit_sequence_vocabulary,
)
from .pipeline import CallableTransformer, ConversationTransformer, FeaturePipeline, FeatureRecord
from .plugins import PluginInfo, list_plugins, load_rule, load_tokenizer
from .policies import (
    HuggingFaceTokenCounter,
    ReplyChainPolicy,
    TiktokenTokenCounter,
    TimeWindowPolicy,
    TokenBudgetPolicy,
    TokenCounter,
    TurnWindowPolicy,
    Utf8ByteTokenCounter,
    WhitespaceTokenCounter,
)
from .profiles import Profile, get_profile, load_profiles
from .redaction import RedactionPolicy, RedactionReport, redact_conversations, redact_stream
from .search import ConversationSearchIndex, SearchHit
from .service import TurnScopeService, create_server
from .sparse import SparseSimilarityIndex, VectorMatch, normalize_sparse, sparse_cosine
from .tabular import window_rows, windows_csv, write_windows_csv
from .transformers import (
    ConversationFeatures,
    CoordinationScore,
    CorpusSpeakerProfile,
    DiversityProfile,
    SpeakerProfile,
    TfidfState,
    TfidfVectorizer,
    conversation_features,
    corpus_speaker_profiles,
    default_coordination_categories,
    linguistic_coordination,
    linguistic_diversity,
    speaker_profiles,
)

__all__ = [
    "AuditReport",
    "Auditor",
    "CallableTransformer",
    "ChatFormat",
    "ClassifierState",
    "ClusterState",
    "ContextBuilder",
    "ContextEdge",
    "ContextPair",
    "ContextPrediction",
    "ContextProjection",
    "ContextRecord",
    "ContextWindow",
    "Conversation",
    "ConversationClassifier",
    "ConversationFeatures",
    "ConversationSearchIndex",
    "ConversationTransformer",
    "CoordinationScore",
    "CorpusSpeakerProfile",
    "CorpusStore",
    "DirectionPrediction",
    "DirectionState",
    "DiversityProfile",
    "DualContextConfig",
    "DualContextModel",
    "DualContextPrediction",
    "DualContextState",
    "EncodedPrefix",
    "ExpectedContextModel",
    "ExpectedContextState",
    "FeaturePipeline",
    "FeatureRecord",
    "ForecastDataset",
    "ForecastExample",
    "ForecastPrediction",
    "ForecastPrefix",
    "ForecastState",
    "HierarchicalEventForecaster",
    "HuggingFaceTokenCounter",
    "InteractionEdge",
    "InteractionNetwork",
    "InteractionNetworkAccumulator",
    "Issue",
    "NetworkCentrality",
    "NetworkEdge",
    "NetworkMetrics",
    "NeuralArchitecture",
    "NeuralArtifactError",
    "NeuralArtifactLimits",
    "NeuralEpoch",
    "NeuralForecastConfig",
    "NeuralForecastPrediction",
    "NeuralForecastState",
    "NeuralNumericLimits",
    "NeuralSaveResult",
    "NeuralTrainingConfig",
    "NeuralTrainingResult",
    "ObservedPrefix",
    "ObservedTurn",
    "PluginInfo",
    "PrefixEventForecaster",
    "Profile",
    "RedactionPolicy",
    "RedactionReport",
    "ReplyChainPolicy",
    "ReplyCoordinationScore",
    "ReplyForest",
    "SearchHit",
    "SequenceAudit",
    "SequenceDataError",
    "SequenceForecastDataset",
    "SequenceForecastExample",
    "SequenceLimitError",
    "SequenceLimits",
    "SequencePolicy",
    "SequenceVocabulary",
    "Severity",
    "SparseSimilarityIndex",
    "SpeakerProfile",
    "SpeakerSummary",
    "TfidfState",
    "TfidfVectorizer",
    "TiktokenTokenCounter",
    "TimeWindowPolicy",
    "TokenBudgetPolicy",
    "TokenCounter",
    "TurnScopeService",
    "TurnWindowPolicy",
    "Utf8ByteTokenCounter",
    "Utterance",
    "VectorMatch",
    "WhitespaceTokenCounter",
    "adapt_anthropic",
    "adapt_conversation",
    "adapt_convokit",
    "adapt_openai",
    "adapt_sharegpt",
    "conversation_features",
    "corpus_speaker_profiles",
    "create_server",
    "default_auditor",
    "default_coordination_categories",
    "encode_observed_prefix",
    "evaluate_dual_context",
    "fit_sequence_vocabulary",
    "get_profile",
    "interaction_edges",
    "interaction_network",
    "iter_adapted_conversations",
    "iter_adapted_convokit_jsonl",
    "iter_adapted_jsonl",
    "iter_adapted_path",
    "iter_context_pairs",
    "iter_conversations",
    "iter_path",
    "linguistic_coordination",
    "linguistic_diversity",
    "list_plugins",
    "load_neural_forecaster",
    "load_profiles",
    "load_rule",
    "load_tokenizer",
    "normalize_sparse",
    "observed_prefix",
    "prepare_forecast_examples",
    "prepare_sequence_forecasts",
    "redact_conversations",
    "redact_stream",
    "reply_coordination",
    "reply_forest",
    "save_neural_forecaster",
    "sparse_cosine",
    "speaker_profiles",
    "window_rows",
    "windows_csv",
    "write_windows_csv",
]

__version__ = "0.2.0"
